#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import json
import subprocess

MODES = json.loads(os.getenv('MODES'))
OUTDIR = os.environ['OUTDIR']
API_KEY = os.environ['API_KEY']
USER = os.environ['USERNAME']


def outstream(filename):
    return open(filename, "w")


def instream(filename):
    return open(filename, "r")


def get_output_filename(odir):
    return "%s/Unglueit.csv" % (odir)


def get_publisher_id(config_list):
    vals = []
    for c in config_list:
        if c['name'] == 'publisher':
            vals.append('--' + c['name'])
            vals.append(c['value'])
    return vals


def run():
    i = 0
    out_file = get_output_filename(OUTDIR)
    output_stream = outstream(out_file)
    for m in MODES:
        # only include headers in first iteration
        headers = ['--add-headers'] if i == 0 else []
        i += 1
        cmd = ['./retrieve_stats',
               '--measure', m['measure'],
               '--key', API_KEY,
               '--username', USER] + get_publisher_id(m['config']) + headers
        subprocess.call(cmd, stdout=output_stream)


if __name__ == '__main__':
    run()
